"""
SSI-ENN BESS — Advanced Layer 3 Modules (v3.5)
================================================
Five advanced modules that upgrade Layer 3's ability to feed Layer 2:

  A. Config A Parallel Predictions  — Dual-config NN (A+B NPV envelopes)
  B. Jacobian Sensitivity Engine    — ∂NPV/∂feature for what-if analysis
  C. Scenario Stress Testing        — Extreme input perturbation validation
  D. Model Monitoring / Drift       — PSI + feature distribution tracking
  E. Ensemble Uncertainty           — Epistemic vs aleatoric decomposition

All modules operate on the trained models from nn_trainer.py and extend
the NeuralNetworkTrainer class with additional methods.
"""

import json
import time
from pathlib import Path
from copy import deepcopy

import numpy as np
import pandas as pd
from scipy.stats import spearmanr
from sklearn.neural_network import MLPRegressor
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_absolute_error, r2_score

from pipeline.nn_trainer import (
    NeuralNetworkTrainer, FeatureEngineer, ALL_FEATURES,
    MULTI_TARGETS, MULTI_TARGET_LABELS, REVENUE_STREAMS, REVENUE_STREAM_NAMES,
)


# ═══════════════════════════════════════════════════════════════
# Module A: Config A Parallel Predictions
# ═══════════════════════════════════════════════════════════════

class DualConfigTrainer:
    """Train a separate multi-target regressor for Config A.

    Uses mc_results_A from data.json (generated by run_fleet_mc with config='A').
    Produces: NPV_A P5/P50/P95, IRR_A, Sharpe_A — parallel to Config B targets.
    """

    TARGETS_A = ['npv_A_P5', 'npv_A_P50', 'npv_A_P95', 'irr_A', 'sharpe_A']
    LABELS_A = ['NPV_A P5', 'NPV_A P50', 'NPV_A P95', 'IRR_A', 'Sharpe_A']

    def __init__(self, trainer: NeuralNetworkTrainer):
        self.trainer = trainer
        self.df = trainer.df
        self.X_train = trainer.X_train
        self.X_test = trainer.X_test
        self.train_idx = trainer.train_idx
        self.test_idx = trainer.test_idx
        self.scaler = trainer.scaler
        self.X = trainer.X

    def _extract_config_a_targets(self, substations: list) -> pd.DataFrame:
        """Extract Config A MC targets from substations."""
        rows = []
        for s in substations:
            mc_a = s.get('mc_results_A', {})
            rows.append({
                'npv_A_P5': mc_a.get('npv', {}).get('npv_P5', 0),
                'npv_A_P50': mc_a.get('npv', {}).get('npv_P50', 0),
                'npv_A_P95': mc_a.get('npv', {}).get('npv_P95', 0),
                'irr_A': mc_a.get('irr', {}).get('irr_median', 0),
                'sharpe_A': mc_a.get('risk', {}).get('sharpe_ratio', 0),
            })
        return pd.DataFrame(rows)

    def train(self, substations: list, verbose: bool = True) -> dict:
        """Train Config A multi-target regressor."""
        if verbose:
            print(f"\n[A] Config A Multi-Target Regressor — MLP(512,256,128)")
            print(f"{'-'*70}")

        df_a = self._extract_config_a_targets(substations)

        Y = df_a[self.TARGETS_A].fillna(0).values.astype(np.float64)
        Y_train, Y_test = Y[self.train_idx], Y[self.test_idx]

        base_model = MLPRegressor(
            hidden_layer_sizes=(512, 256, 128),
            activation='relu', solver='adam', alpha=1e-3,
            learning_rate='adaptive', max_iter=500,
            random_state=42,
            early_stopping=True, validation_fraction=0.1,
            n_iter_no_change=20,
        )
        model = MultiOutputRegressor(base_model, n_jobs=-1)
        model.fit(self.X_train, Y_train)

        pred_test = model.predict(self.X_test)
        pred_train = model.predict(self.X_train)

        per_target = {}
        for j, (name, label) in enumerate(zip(self.TARGETS_A, self.LABELS_A)):
            yt, yp = Y_test[:, j], pred_test[:, j]
            yt_tr, yp_tr = Y_train[:, j], pred_train[:, j]
            sp, _ = spearmanr(yt, yp)
            per_target[name] = {
                'label': label,
                'mae_test': round(float(mean_absolute_error(yt, yp)), 4),
                'r2_test': round(float(r2_score(yt, yp)), 4),
                'spearman': round(float(sp), 4),
            }

        # Delta analysis: A vs B
        X_all = self.scaler.transform(self.X)
        pred_A_all = model.predict(X_all)
        pred_B_all = self.trainer.models.get('multi_target', self.trainer.models.get('npv_regressor')).predict(X_all)

        if pred_B_all.ndim == 2:
            delta_npv = pred_B_all[:, 1] - pred_A_all[:, 1]  # B_P50 - A_P50
        else:
            delta_npv = pred_B_all - pred_A_all[:, 1]

        metrics = {
            'per_target': per_target,
            'delta_npv_mean_M': round(float(delta_npv.mean()), 4),
            'delta_npv_std_M': round(float(delta_npv.std()), 4),
            'pct_B_dominates': round(float(np.mean(delta_npv > 0) * 100), 1),
        }

        if verbose:
            for name, tm in per_target.items():
                print(f"  {tm['label']:12s}  MAE={tm['mae_test']:.4f}  R²={tm['r2_test']:.4f}  ρ={tm['spearman']:.4f}")
            print(f"  ΔN PV (B−A) mean: €{metrics['delta_npv_mean_M']:.2f}M ± €{metrics['delta_npv_std_M']:.2f}M")
            print(f"  Config B dominates: {metrics['pct_B_dominates']:.1f}% of substations")

        return model, metrics


# ═══════════════════════════════════════════════════════════════
# Module B: Jacobian Sensitivity Engine
# ═══════════════════════════════════════════════════════════════

class SensitivityEngine:
    """Compute ∂NPV/∂feature for each substation via numerical differentiation.

    Provides Layer 2 with per-substation sensitivity vectors:
    "If feature X increases by 1 unit, NPV changes by Y €M."
    """

    def __init__(self, trainer: NeuralNetworkTrainer, epsilon: float = 0.01):
        self.trainer = trainer
        self.epsilon = epsilon
        self.model = trainer.models.get('multi_target', trainer.models.get('npv_regressor'))
        self.scaler = trainer.scaler

    def _predict_p50(self, X_scaled):
        pred = self.model.predict(X_scaled)
        if pred.ndim == 2:
            return pred[:, 1]
        return pred

    def compute_jacobian(self, n_sample: int = 500, verbose: bool = True) -> dict:
        """Compute numerical Jacobian for a sample of substations.

        Returns:
            dict with 'jacobian' (n_sample × n_features), 'global_sensitivity',
            and 'per_substation' sensitivities.
        """
        if verbose:
            print(f"\n[B] Jacobian Sensitivity Engine (ε={self.epsilon}, n={n_sample})")
            print(f"{'-'*70}")

        rng = np.random.RandomState(42)
        n_total = len(self.trainer.X)
        sample_idx = rng.choice(n_total, size=min(n_sample, n_total), replace=False)

        X_sample = self.trainer.X[sample_idx]
        X_scaled = self.scaler.transform(X_sample)
        base_pred = self._predict_p50(X_scaled)

        n_features = X_sample.shape[1]
        jacobian = np.zeros((len(sample_idx), n_features))

        for j in range(n_features):
            X_pert = X_scaled.copy()
            # Perturb by epsilon in scaled space
            X_pert[:, j] += self.epsilon
            pert_pred = self._predict_p50(X_pert)
            jacobian[:, j] = (pert_pred - base_pred) / self.epsilon

        # Global sensitivity: mean |∂NPV/∂feature|
        global_sens = np.abs(jacobian).mean(axis=0)
        fi_sorted = np.argsort(global_sens)[::-1]

        top_sensitivities = [
            {
                'feature': ALL_FEATURES[i],
                'mean_abs_sensitivity': round(float(global_sens[i]), 4),
                'direction': 'positive' if jacobian[:, i].mean() > 0 else 'negative',
            }
            for i in fi_sorted[:15]
        ]

        # Per-substation top-3 sensitivities
        per_sub = {}
        for k, idx in enumerate(sample_idx):
            sub_id = self.trainer.df.iloc[idx]['substation_id']
            jac = jacobian[k]
            top3_idx = np.argsort(np.abs(jac))[::-1][:3]
            per_sub[sub_id] = [
                {'feature': ALL_FEATURES[j], 'dNPV_per_unit': round(float(jac[j]), 4)}
                for j in top3_idx
            ]

        metrics = {
            'n_substations': len(sample_idx),
            'n_features': n_features,
            'epsilon': self.epsilon,
            'top_sensitivities': top_sensitivities,
            'per_substation_count': len(per_sub),
        }

        if verbose:
            print(f"  Computed {len(sample_idx)} × {n_features} Jacobian matrix")
            print(f"  Top global sensitivities:")
            for s in top_sensitivities[:10]:
                print(f"    {s['feature']:25s}  |∂NPV/∂f|={s['mean_abs_sensitivity']:.4f}  dir={s['direction']}")

        return {'jacobian': jacobian, 'sample_idx': sample_idx, 'metrics': metrics,
                'global': top_sensitivities, 'per_substation': per_sub}


# ═══════════════════════════════════════════════════════════════
# Module C: Scenario Stress Testing
# ═══════════════════════════════════════════════════════════════

class ScenarioStressTester:
    """Validate NN behaviour under extreme deterministic scenarios.

    Tests whether the NN extrapolates sensibly when inputs are pushed
    to extremes that represent real-world crisis conditions.
    """

    SCENARIOS = {
        'gas_crisis': {
            'description': 'Prolonged gas supply disruption — higher risk metrics dominate',
            'perturbations': {
                'fuel_shock_exposure': +0.40,  # High fuel shock risk
                'bess_fuel_upside': +0.30,     # Upside exists but risk dominates
                'bs_composite': +0.20,         # Higher black swan risk
            },
            'expected_direction': 'mixed',  # Risk ↑ competes with opportunity ↑
        },
        'rapid_decarbonisation': {
            'description': 'Accelerated EU 2035 targets achieved by 2030',
            'perturbations': {
                'decarb_discount': -0.20,       # Lower conventional ratio
                'fuel_shock_exposure': -0.15,   # Less fuel dependence
                'revenue_haircut_pct': +5.0,    # More cannibalization from renewables
            },
            'expected_direction': 'negative',  # Net negative for BESS arbitrage
        },
        'grid_congestion_spike': {
            'description': 'Massive renewable buildout + congestion + saturation',
            'perturbations': {
                'congestion_factor': +0.30,     # Severe congestion (risk ↑)
                'crs_nodal': +0.15,             # Nodal pricing shift
                'crs_uplift_pct': +10.0,        # Larger zonal→nodal uplift
                'bess_sat': +0.10,              # More BESS deployed
            },
            'expected_direction': 'mixed',  # Congestion risk vs nodal opportunity
        },
        'regulatory_collapse': {
            'description': 'Capacity market suspended, FCR rules changed',
            'perturbations': {
                'revenue_haircut_pct': +15.0,   # Severe haircut
                'exposure_index': +0.20,        # High exposure
                'bs_composite': +0.25,          # High regulatory risk
            },
            'expected_direction': 'negative',  # Clear negative
        },
        'perfect_storm': {
            'description': 'Gas crisis + grid congestion + high saturation + regulatory risk',
            'perturbations': {
                'fuel_shock_exposure': +0.40,
                'bess_fuel_upside': +0.30,
                'congestion_factor': +0.30,
                'bess_sat': +0.15,
                'revenue_haircut_pct': +8.0,
                'bs_composite': +0.30,
            },
            'expected_direction': 'negative',  # Multiple risk factors dominate
        },
    }

    def __init__(self, trainer: NeuralNetworkTrainer):
        self.trainer = trainer
        self.model = trainer.models.get('multi_target', trainer.models.get('npv_regressor'))
        self.scaler = trainer.scaler

    def _predict_p50(self, X_scaled):
        pred = self.model.predict(X_scaled)
        return pred[:, 1] if pred.ndim == 2 else pred

    def run_all_scenarios(self, verbose: bool = True) -> dict:
        """Run all stress scenarios and validate NN response.

        Perturbations are clipped to [P1, P99] of training data to keep
        the NN inside its interpolation domain — MLPs extrapolate poorly.
        """
        if verbose:
            print(f"\n[C] Scenario Stress Testing ({len(self.SCENARIOS)} scenarios)")
            print(f"{'-'*70}")

        # Compute per-feature bounds from training data (P1–P99)
        X_raw = self.trainer.X
        feat_lo = np.percentile(X_raw, 1, axis=0)
        feat_hi = np.percentile(X_raw, 99, axis=0)

        X_all = self.scaler.transform(X_raw)
        base_pred = self._predict_p50(X_all)
        base_median = float(np.median(base_pred))

        results = {}
        n_pass = 0

        for name, scenario in self.SCENARIOS.items():
            # Apply perturbations to unscaled features, then clip to training range
            X_pert = X_raw.copy()
            for feature, delta in scenario['perturbations'].items():
                if feature in ALL_FEATURES:
                    j = ALL_FEATURES.index(feature)
                    X_pert[:, j] = np.clip(X_pert[:, j] + delta, feat_lo[j], feat_hi[j])

            X_pert_scaled = self.scaler.transform(X_pert)
            stressed_pred = self._predict_p50(X_pert_scaled)
            stressed_median = float(np.median(stressed_pred))

            delta_pct = (stressed_median - base_median) / base_median * 100
            actual_dir = 'positive' if delta_pct > 1 else ('negative' if delta_pct < -1 else 'neutral')
            expected = scenario['expected_direction']

            if expected == 'mixed':
                direction_ok = True  # Any direction acceptable
            elif expected == 'positive':
                direction_ok = delta_pct > -2  # Allow small negative
            else:
                direction_ok = delta_pct < 2   # Allow small positive

            n_pass += int(direction_ok)

            results[name] = {
                'description': scenario['description'],
                'base_median_M': round(base_median, 4),
                'stressed_median_M': round(stressed_median, 4),
                'delta_pct': round(delta_pct, 2),
                'actual_direction': actual_dir,
                'expected_direction': expected,
                'direction_ok': direction_ok,
                'n_extreme_moves': int(np.sum(np.abs(stressed_pred - base_pred) > 2 * np.std(base_pred))),
            }

            if verbose:
                status = '✓' if direction_ok else '✗'
                print(f"  {status} {name:25s}  Δ={delta_pct:+6.2f}%  "
                      f"({actual_dir:8s} vs expected {expected:8s})  "
                      f"€{stressed_median:.2f}M")

        metrics = {
            'n_scenarios': len(self.SCENARIOS),
            'n_pass': n_pass,
            'pass_rate': round(n_pass / len(self.SCENARIOS) * 100, 1),
            'scenarios': results,
            'stress_stable': n_pass >= len(self.SCENARIOS) - 1,
        }

        if verbose:
            print(f"  Pass rate: {metrics['pass_rate']:.0f}% ({n_pass}/{len(self.SCENARIOS)})")
            print(f"  Stress stable: {'YES' if metrics['stress_stable'] else 'NO'}")

        return metrics


# ═══════════════════════════════════════════════════════════════
# Module D: Model Monitoring / Drift Detection
# ═══════════════════════════════════════════════════════════════

class DriftMonitor:
    """Detect when model retraining is needed.

    Uses Population Stability Index (PSI) to track feature and prediction
    distribution shifts between training and new data.
    """

    @staticmethod
    def _psi(expected: np.ndarray, actual: np.ndarray, n_bins: int = 10) -> float:
        """Compute Population Stability Index."""
        # Create bins from expected distribution
        breakpoints = np.quantile(expected, np.linspace(0, 1, n_bins + 1))
        breakpoints[0] = -np.inf
        breakpoints[-1] = np.inf

        expected_counts = np.histogram(expected, bins=breakpoints)[0]
        actual_counts = np.histogram(actual, bins=breakpoints)[0]

        # Add smoothing to avoid log(0)
        expected_pct = (expected_counts + 1) / (len(expected) + n_bins)
        actual_pct = (actual_counts + 1) / (len(actual) + n_bins)

        psi = np.sum((actual_pct - expected_pct) * np.log(actual_pct / expected_pct))
        return float(psi)

    def __init__(self, trainer: NeuralNetworkTrainer):
        self.trainer = trainer

    def compute_baseline(self, verbose: bool = True) -> dict:
        """Compute baseline distributions from training data for future monitoring."""
        if verbose:
            print(f"\n[D] Model Monitoring — Baseline Computation")
            print(f"{'-'*70}")

        X_train = self.trainer.X[self.trainer.train_idx]
        X_test = self.trainer.X[self.trainer.test_idx]

        # Feature distribution baselines
        feature_stats = {}
        for j, feat in enumerate(ALL_FEATURES):
            train_vals = X_train[:, j]
            feature_stats[feat] = {
                'mean': round(float(np.mean(train_vals)), 6),
                'std': round(float(np.std(train_vals)), 6),
                'p5': round(float(np.percentile(train_vals, 5)), 6),
                'p95': round(float(np.percentile(train_vals, 95)), 6),
            }

        # Prediction distribution baseline
        model = self.trainer.models.get('multi_target', self.trainer.models.get('npv_regressor'))
        X_train_scaled = self.trainer.scaler.transform(X_train)
        pred_train = model.predict(X_train_scaled)
        if pred_train.ndim == 2:
            p50_train = pred_train[:, 1]
        else:
            p50_train = pred_train

        pred_stats = {
            'mean': round(float(np.mean(p50_train)), 4),
            'std': round(float(np.std(p50_train)), 4),
            'p5': round(float(np.percentile(p50_train, 5)), 4),
            'p95': round(float(np.percentile(p50_train, 95)), 4),
        }

        # Compute train vs test PSI as reference
        feature_psi = {}
        for j, feat in enumerate(ALL_FEATURES):
            psi = self._psi(X_train[:, j], X_test[:, j])
            feature_psi[feat] = round(psi, 6)

        # Sort by PSI (highest drift features)
        psi_sorted = sorted(feature_psi.items(), key=lambda x: x[1], reverse=True)

        X_test_scaled = self.trainer.scaler.transform(X_test)
        pred_test = model.predict(X_test_scaled)
        if pred_test.ndim == 2:
            p50_test = pred_test[:, 1]
        else:
            p50_test = pred_test

        pred_psi = self._psi(p50_train, p50_test)

        n_drifted = sum(1 for _, psi in psi_sorted if psi > 0.10)

        metrics = {
            'n_features': len(ALL_FEATURES),
            'feature_psi': dict(psi_sorted[:10]),
            'prediction_psi': round(pred_psi, 6),
            'n_features_drifted': n_drifted,
            'drift_threshold': 0.10,
            'retrain_recommended': pred_psi > 0.20 or n_drifted > 5,
            'feature_baselines': feature_stats,
            'prediction_baseline': pred_stats,
        }

        if verbose:
            print(f"  Train/test PSI (prediction): {pred_psi:.6f}")
            print(f"  Features with PSI > 0.10:    {n_drifted}/{len(ALL_FEATURES)}")
            print(f"  Top drifted features:")
            for feat, psi in psi_sorted[:5]:
                status = '⚠' if psi > 0.10 else '✓'
                print(f"    {status} {feat:25s}  PSI={psi:.6f}")
            print(f"  Retrain recommended: {'YES' if metrics['retrain_recommended'] else 'NO'}")

        return metrics


# ═══════════════════════════════════════════════════════════════
# Module E: Ensemble Uncertainty Decomposition
# ═══════════════════════════════════════════════════════════════

class EnsembleUncertainty:
    """Decompose prediction uncertainty into epistemic and aleatoric.

    Uses bootstrap ensemble: train N models on bootstrap samples.
    - Epistemic uncertainty = variance across models (fixable with more data)
    - Aleatoric uncertainty = mean of within-model variance (irreducible)

    Investment committees need this: "we're uncertain because we lack data"
    vs "we're uncertain because the market is genuinely volatile."
    """

    def __init__(self, trainer: NeuralNetworkTrainer, n_models: int = 10):
        self.trainer = trainer
        self.n_models = n_models

    def train_ensemble(self, verbose: bool = True) -> dict:
        """Train bootstrap ensemble and decompose uncertainty."""
        if verbose:
            print(f"\n[E] Ensemble Uncertainty Decomposition ({self.n_models} bootstrap models)")
            print(f"{'-'*70}")

        rng = np.random.RandomState(42)
        X_train = self.trainer.X_train
        Y_train = self.trainer.df[MULTI_TARGETS].fillna(0).values[self.trainer.train_idx]

        # Train N bootstrap models
        models = []
        for i in range(self.n_models):
            # Bootstrap sample (with replacement)
            n = len(X_train)
            boot_idx = rng.choice(n, size=n, replace=True)
            X_boot = X_train[boot_idx]
            Y_boot = Y_train[boot_idx]

            base = MLPRegressor(
                hidden_layer_sizes=(256, 128),  # Slightly smaller for speed
                activation='relu', solver='adam', alpha=1e-3,
                learning_rate='adaptive', max_iter=300,
                random_state=42 + i,
                early_stopping=True, validation_fraction=0.1,
                n_iter_no_change=15,
            )
            model = MultiOutputRegressor(base, n_jobs=-1)
            model.fit(X_boot, Y_boot)
            models.append(model)
            if verbose:
                print(f"  Model {i+1}/{self.n_models} trained", end='\r')

        if verbose:
            print(f"  All {self.n_models} models trained             ")

        # Predict with all models on full dataset
        X_all_scaled = self.trainer.scaler.transform(self.trainer.X)
        all_predictions = np.zeros((self.n_models, len(self.trainer.X)))

        for i, model in enumerate(models):
            pred = model.predict(X_all_scaled)
            if pred.ndim == 2:
                all_predictions[i] = pred[:, 1]  # P50
            else:
                all_predictions[i] = pred

        # Decompose uncertainty
        # Epistemic: variance across models (what the model doesn't know)
        epistemic = np.var(all_predictions, axis=0)

        # Total variance from MC: compare ensemble mean to actual MC targets
        mc_p50 = self.trainer.df['npv_b'].values
        ensemble_mean = np.mean(all_predictions, axis=0)
        total_residual_var = (ensemble_mean - mc_p50) ** 2

        # Aleatoric: MC-derived spread (P95 - P5) as proxy for irreducible variance
        mc_p5 = self.trainer.df['npv_P5'].values
        mc_p95 = self.trainer.df['npv_P95'].values
        aleatoric = ((mc_p95 - mc_p5) / 3.29) ** 2  # Approximate variance from 90% CI

        # Fractions
        total = epistemic + aleatoric + 1e-10
        epistemic_frac = epistemic / total
        aleatoric_frac = aleatoric / total

        # Per-substation uncertainty classification
        per_sub = {}
        for i in range(len(self.trainer.df)):
            sub_id = self.trainer.df.iloc[i]['substation_id']
            per_sub[sub_id] = {
                'epistemic_M2': round(float(epistemic[i]), 6),
                'aleatoric_M2': round(float(aleatoric[i]), 6),
                'epistemic_pct': round(float(epistemic_frac[i] * 100), 1),
                'uncertainty_type': 'data_limited' if epistemic_frac[i] > 0.5 else 'market_volatile',
                'ensemble_std_M': round(float(np.sqrt(epistemic[i])), 4),
                'ensemble_mean_M': round(float(ensemble_mean[i]), 4),
            }

        # Global statistics
        metrics = {
            'n_models': self.n_models,
            'epistemic_mean_M2': round(float(np.mean(epistemic)), 6),
            'aleatoric_mean_M2': round(float(np.mean(aleatoric)), 6),
            'epistemic_pct_fleet': round(float(np.mean(epistemic_frac) * 100), 1),
            'aleatoric_pct_fleet': round(float(np.mean(aleatoric_frac) * 100), 1),
            'n_data_limited': int(np.sum(epistemic_frac > 0.5)),
            'n_market_volatile': int(np.sum(epistemic_frac <= 0.5)),
            'ensemble_std_mean_M': round(float(np.mean(np.sqrt(epistemic))), 4),
            'ensemble_agreement': round(float(np.mean(np.std(all_predictions, axis=0) < 0.5)), 4),
            'per_substation_count': len(per_sub),
        }

        if verbose:
            print(f"  Epistemic (model uncertainty): {metrics['epistemic_pct_fleet']:.1f}% of total")
            print(f"  Aleatoric (market volatility): {metrics['aleatoric_pct_fleet']:.1f}% of total")
            print(f"  Data-limited substations:      {metrics['n_data_limited']}")
            print(f"  Market-volatile substations:   {metrics['n_market_volatile']}")
            print(f"  Ensemble std (mean):           €{metrics['ensemble_std_mean_M']:.4f}M")
            print(f"  Model agreement (std<€0.5M):   {metrics['ensemble_agreement']*100:.1f}%")

        return {'models': models, 'predictions': all_predictions,
                'metrics': metrics, 'per_substation': per_sub}


# ═══════════════════════════════════════════════════════════════
# Orchestrator: Run All 5 Advanced Modules
# ═══════════════════════════════════════════════════════════════

def run_all_advanced(trainer: NeuralNetworkTrainer, substations: list,
                     verbose: bool = True) -> dict:
    """Run all 5 advanced Layer 3 modules and return combined metrics."""
    t0 = time.time()

    if verbose:
        print(f"\n{'='*70}")
        print(f"  SSI-ENN BESS — Advanced Layer 3 Modules (v3.5)")
        print(f"{'='*70}")

    results = {}

    # A. Config A Parallel
    dual = DualConfigTrainer(trainer)
    model_a, metrics_a = dual.train(substations, verbose=verbose)
    results['config_a'] = metrics_a
    results['config_a_model'] = model_a

    # B. Sensitivity Engine
    sens = SensitivityEngine(trainer)
    sens_results = sens.compute_jacobian(verbose=verbose)
    results['sensitivity'] = sens_results['metrics']
    results['sensitivity_global'] = sens_results['global']
    results['sensitivity_per_sub'] = sens_results['per_substation']

    # C. Stress Testing
    stress = ScenarioStressTester(trainer)
    results['stress'] = stress.run_all_scenarios(verbose=verbose)

    # D. Drift Monitoring
    drift = DriftMonitor(trainer)
    results['drift'] = drift.compute_baseline(verbose=verbose)

    # E. Ensemble Uncertainty
    ensemble = EnsembleUncertainty(trainer, n_models=10)
    ens_results = ensemble.train_ensemble(verbose=verbose)
    results['ensemble'] = ens_results['metrics']
    results['ensemble_per_sub'] = ens_results['per_substation']

    duration = time.time() - t0

    if verbose:
        print(f"\n{'='*70}")
        print(f"  ADVANCED MODULES COMPLETE — {duration:.1f}s")
        print(f"{'='*70}")
        print(f"  [A] Config A:    5-target regressor trained")
        print(f"  [B] Sensitivity: {results['sensitivity']['n_substations']} substations × {results['sensitivity']['n_features']} features")
        print(f"  [C] Stress:      {results['stress']['pass_rate']:.0f}% scenarios pass")
        print(f"  [D] Drift:       retrain={'YES' if results['drift']['retrain_recommended'] else 'NO'}")
        print(f"  [E] Ensemble:    {results['ensemble']['epistemic_pct_fleet']:.1f}% epistemic / {results['ensemble']['aleatoric_pct_fleet']:.1f}% aleatoric")

    results['_meta'] = {
        'version': 3.5,
        'duration_s': round(duration, 2),
        'modules': ['config_a', 'sensitivity', 'stress', 'drift', 'ensemble'],
    }

    return results
